#!/bin/sh
PICS=../db/funny-pics/pics.csv
DELETE=../db/funny-pics/delete.csv

echo '"sid","url"' >$PICS
echo '"example","http://cdn.meme.am/instances/500x/64647060.jpg"' >> $PICS
echo '"example","http://cdn.meme.am/instances/500x/41586830.jpg"' >> $PICS
echo '"sid","url"' >$DELETE

chown www-data:www-data $PICS $DELETE
