#!/bin/sh

GATEWAY=`VBoxManage list runningvms|grep gateway_vm_gateway|cut -f1 -d" "|sed -e s/\"//g`
VBoxManage controlvm $GATEWAY nic3 hostonly vboxnet0
sudo ip route add 172.23.42.0/24 via 172.23.42.129 dev vboxnet0
echo "nameserver 172.23.42.129" |sudo tee /etc/resolv.conf
